// <auto-generated />
using EmployeeManagement.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Coomments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            Email = "mark@pragimtech.com",
                            Name = "Mark"
                        },
                        new
                        {
                            Id = 2,
                            Department = 3,
                            Email = "stu.siegel@yahoo.com",
                            Name = "Stu"
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "MaryD@gmail.com",
                            Name = "Mary Duckworth"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Awesome Opportunity",
                            CompanyName = "CVS",
                            Description = "Master of all",
                            Rating = 0,
                            Title = "Sr Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            Comments = "Java's a job ",
                            CompanyName = "USAA",
                            Description = "Use Java",
                            Rating = 2,
                            Title = "Sr Engineer"
                        },
                        new
                        {
                            Id = 3,
                            Comments = "Who doesn't love golf",
                            CompanyName = "PGA",
                            Description = "Leaving the dream",
                            Rating = 4,
                            Title = "Golf Pro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
